import { Geist, Geist_Mono } from "next/font/google";
import { CSVProvider } from "@/context/CSVContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { LinkOutProvider } from "@/context/LinkOutContext";
import { TagsProvider } from "@/context/TagsContext";

import SessionWrapper from "@/components/SessionWrapper/SessionWrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SessionWrapper>
          <CSVProvider>
            <LinkOutProvider>
              <TagsProvider>
                <SidebarProvider>
                  {children}
                  <div id="modal-root"></div>
                </SidebarProvider>
              </TagsProvider>
            </LinkOutProvider>
          </CSVProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
