import { Geist, Geist_Mono } from "next/font/google";
import { CSVProvider } from "@/context/CSVContext";
import { SidebarProvider } from "@/context/SidebarContext";
import SessionWrapper from "@/components/SessionWrapper/SessionWrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SessionWrapper>
          <CSVProvider>
            <SidebarProvider>{children}</SidebarProvider>
          </CSVProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
