const dataTypes = {
  CountyName: "string",
  Referral_ID: "number",
  Youth_ID: "number",
  Record_ID: "number",
  Gender: "string",
  Race: "string",
  Ethnicity: "string",
  Hispanic: "number",
  Home_Zip_Code: "number",
  Home_Language: null,
  Date_of_Birth: ["string", "number"],
  Facility: "string",
  Offense: "string",
  OffenseCategory: "string",
  Post_Adjudicated_Status: "string",
  Adult_Court: "number",
  Admission_Date: ["string", "number"],
  Admission_Time: "string",
  Release_Date: ["string", "number"],
  Release_Time: "string",
  Referral_Source: "string",
  Release_Stage: "string",
  Release_Stage_Other: null,
  Booking_Date: null,
  Booking_Time: null,
  Intake_Date: ["string", "number"],
  Intake_Time: "string",
  Intake_Decision: "string",
  RiskLevel: "string",
  DST_Score: "number",
  MediumCutoff: "number",
  HighCutoff: "number",
  Auto_Hold: "number",
  Override_Reason: "string",
  Auto_Hold_Reason: null,
  ATD_Program_Name: "string",
  DispositionDate: ["string", "number"],
  ATD_Entry_Date: ["string", "number"],
  ATD_Entry_Time: "string",
  ATD_Exit_Date: ["string", "number"],
  ATD_Exit_Time: "string",
  ATD_Successful_Exit: "number",
  ATD_Exit_FTA: "number",
  ATD_Exit_New_Offense: "number",
  ATD_Exit_Technical: "number",
  ATD_Exit_Other: "number",
  ATD_Exit_Specify_Other: "string",
  Hearing_Type: null,
  Hearing_Outcome: null,
  Hearing_Date: null,
  Hearing_Time: null,
  Exit_To: "string",
  ATD_Reoffense_Type: null,
  Detention_IYAS_Date: null,
  Out_Of_County: "number",
  LawEnforcementAgency: "string",
  AtdProgramCategory: "string",
  "Post-Dispo Stay Reason": "string",
};

export default dataTypes;
